defaults:
  -
    scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: kactus/application
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: kactus/post

about_page: true
author: "John Goldsmith"
baseurl: "/" # the subpath of your site, e.g. /blog/
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
disqus_shortname: 'your-disqus-shortname'
email: hello@creative-dna.net
github_username: john-goldsmith
google_analytics: "UA-XXXXXXXX-X"
highlighter: pygments
logo: false
markdown: kramdown # redcarpet
meta_description: "Code In Plain English"
paginate: 20
permalink: /:year/:month/:day/:title
sass:
  sass_dir: _sass
  style: compressed
theme: kactus
title: Code In Plain English
url: "http://creative-dna.net" # the base hostname & protocol for your site